### ISSUE TITLE
Does not work in internal pages

### ISSUE THREAD

**Issue by firgon** [pushreset/koken-right-click-alert-plugin#1]
Thanks a lot for this very nice plugin, but it works on homepage, in album pages, but not in contents pages, or photo pages on my website with koken 0.9.5 and  axis theme.

It's viewable here : www.phosflore.fr

What have i done wrong ?

Thanks

**Comment by pushreset** [comment]
Hi,

Try to add this css selector "im.img-content" on the field "Custom selector" in plugin settings (and in "append" in "Use custom selector").

Nice photos by the way ;)

ps: français ? :)

**Comment by firgon** [comment]
Thanks for you very quick answer.

Ok, done. But nothing different. 

PS: Oui, français ! Ca s'est vu ?? lol

**Comment by pushreset** [comment]
Oups excuse moi le sélecteur c'est "img.img-content" !

**Comment by firgon** [comment]
C'est mieux !

Ca marche pour les pages pour les photos uniques !!! (et c'est l'essentiel)

Ca ne marche toujours pas pour la galerie "contenus". (mais les images étant réduites, l'impact est moins grave)

Encore merci au nom de tous ceux qui ne s'exprimeront pas et qui utilisent ce petit plugin bien pratique.

**Comment by pushreset** [comment]
Effectivement je n'avais pas vu ces images, essaye avec ces sélecteurs :
"img.k-lazy-loaded, img.img-content".

Si tu as des propositions pour améliorer le plugin n'hésites pas !

A bientôt,

Julien

2013/8/31 firgon notifications@github.com

**Comment by firgon** [comment]
Ok, je n'hésiterai pas !
