### ISSUE TITLE
Nothing showing with Koken 0.11.3

### ISSUE THREAD

**Issue by adrianlambert** [pushreset/koken-right-click-alert-plugin#2]
Just installed this plugin on the above version of koken but it doesn’t show in the plugin listing. I have reset the /storage/cache/api folder and checked owners and permissions. All is fine there. Consistent in safari 7.0.1 and firefox 26 on mac os x 10.9.1.

**Comment by pushreset** [comment]
Is this a fresh install of Koken 0.11.3 or from an update ?

**Comment by pushreset** [comment]
#q2: do you have any other plugins installed ?

**Comment by adrianlambert** [comment]
Bah, stupid me. I uploaded the github master folder with the plugin folder inside. When I got rid of the extra folder it worked fine. Very sorry. It was late in the day! 
Cheers

Adrian Lambert Photography
07581 209 100
http://alp.me.uk/

**Comment by pushreset** [comment]
No worries !
